### ISSUE TITLE
Extenstions Still in Pending State

### ISSUE THREAD

**Issue by atayyala** [stansw/vsts-open-in-powerbi#10]
I have requested permission to this extension and could see that it is stil in Pending state. Could you please give permission to this extension? Thanks,

![image](https://user-images.githubusercontent.com/33538751/32645326-acc251f2-c5de-11e7-8a97-0e183afa39c6.png)

**Comment by stansw** [comment]
@atayyala this extension is publicly available and everyone is welcome to install it. However, in order to do it you need to be in the Project Collection Administrators group. If you were able only to send request it means that you don't have the permissions. Please contact your administrators and let them know that you would like this extension to be installed. 

Here is a link to the documentation about the installation process.
https://docs.microsoft.com/en-us/vsts/marketplace/install-vsts-extension

**Comment by atayyala** [comment]
I'm already a Project admin, I couldn't able to see this link anywhere. Could you please let me know where I need to look at this option.
![image](https://user-images.githubusercontent.com/33538751/32646880-c3d16ee2-c614-11e7-8aa6-ad550ebcd90b.png)
