### ISSUE TITLE
Not able to import VSTS tree queries and Direct links queries

### ISSUE THREAD

**Issue by sriramdasbalaji** [stansw/vsts-open-in-powerbi#6]
Hi 

I am not able to import VSTS Work item Tree Queries/Direct links queries in Power BI. It is giving error as below
**Work Item Links
Expresiion.Error: The field 'workitemrelations' of the record wasn't found**

Is this the limitation? Do we have any alternate way to do this?

**Comment by StanislawSwierc** [comment]
@sriramdasbalaji, thank you for reporting this problem! I did some investigation. Extension expects that the payload will match the schema defined in the official documentation of the REST API, which in fact lists `workItemRelations` as mandatory field. I checked what happens when result is empty and the field is still present as an empty array.

* [Run a stored query](https://www.visualstudio.com/en-us/docs/integrate/api/wit/wiql#run-a-stored-query)

Both direct and tree queries have been supported since the first version of this extension.

* [Tree of Work Items](https://github.com/stansw/vsts-open-in-powerbi/wiki/Tree-of-Work-Items)

That said it does look like a genuine problem! Could you share a screenshot of your query and blurred result so that I can get more information about when this error happens?

**Comment by stansw** [comment]
I found the root cause. Apparently queries of type `oneHop`, when run with `linksOneHopDoesNotContain` query mode, they return work items instead of work item links. I've updated the code and will handle it correctly in the new version that is going to be released today.
